### PR TITLE
Added main role to home page

### PR DESCRIPTION
**Pull request by nick-mon1**
## Summary

Home page was missing `main` tag and role.

**Note**

`main` tag on homepage has no classes or id styles applied because of style differences between other pages, a padding gap from the top navbar that breaks the home page design.

`<main class="usa-layout-docs usa-section" id="main-content">` 

Screen Shot 2022-10-25 at 4 58 41 PM

### CODE REVIEW

**Review by mejiaj — COMMENTED** [review]
Wouldn't this `<main>` element be better for a more generic layout template or is this only happening on the homepage?

**Comment by nick-mon1** [comment]
This is only happening on the main page, the other pages use the `main` element as expected.

**Comment by mejiaj** [comment]
> This is only happening on the main page, the other pages use the `main` element as expected.

Good to know, thanks! One last question; is there a `skip to content` link at the top you can tab to? We might want to add the ID it's pointing to (if it's not already).

**Comment by nick-mon1** [comment]
@mejiaj Good catch, I've re-added the ID to the for the `main` tag for the jump link..

**Review by mejiaj — APPROVED** [review]
Nice change!

**Pull request merged**
