### PR TITLE
Demo banner

### PR DESCRIPTION
**Pull request by jeremyzilar**
This is a banner that will appear on the site while it is in BETA on the demo URL.

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/demo-banner/

### CODE REVIEW

**Comment by mmcmanusOMB** [comment]
Is the link in the demo banner going to open an e-mail box for PRA@omb.eop.gov ?

**Comment by qhirschomb** [comment]
@jeremyzilar Visually, this is a little off putting given the range of different colors (yellow, blue, white, black) in horizontal bars and how small the title of the website and the corresponding menus look. Is there a way to limit the palette or decrease the size of the yellow banner? Just a thought

**Comment by jeremyzilar** [comment]
@mmcmanusOMB it will link to a section on the "About" page that will be about submitting feedback, and will include the `PRA@omb.eop.gov` email.

**Comment by jeremyzilar** [comment]
@qhirschomb — yes, I can make some adjustments to it. 
Though the point of the banner is to make it clear that this is a DEMO site and not the real, live URL. We just borrowed what we had here https://demo.digital.gov/

**Pull request merged**
